RequestUrlList:
  - Platform: gitee
    AuthorizeUrl: https://gitee.com/oauth/authorize
    AccessTokenUrl: https://gitee.com/oauth/token
    UserInfoUrl: https://gitee.com/api/v5/user
  - Platform: wechat_mp
    AuthorizeUrl: https://open.weixin.qq.com/connect/oauth2/authorize
    AccessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token
    UserInfoUrl: https://api.weixin.qq.com/sns/userinfo
    RefreshUrl: https://api.weixin.qq.com/sns/oauth2/refresh_token
